name: physionet_2024
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip:
      - html5lib==1.1
      - joblib==1.3.2
      - numpy==1.26.2
      - pandas==1.5.3
      - pillow==10.2.0
      - scikit-learn==1.3.2
      - wfdb==4.1.2
      - jupyterlab==4.1.4